version: '{build}-{branch}'
clone_depth: 100

configuration:
- Debug
- Release

init:
- ps: >-
    $version = Get-Date -Format "yyyymmddHHmm"
    Update-AppveyorBuild -Version "$version"

build:
  project: build/win32/vs2010/Regal/Regal.sln
  verbosity: normal

after_build:
- cmd: >-
    cd build/win32/vs2010/Regal
    dir
    set ARCHIVE=Regal_Windows_x86_%CONFIGURATION%_%APPVEYOR_BUILD_VERSION%.7z
    7z a %ARCHIVE% %CONFIGURATION%/Win32
    appveyor PushArtifact %ARCHIVE%
